### ISSUE TITLE
Cannot rebuild and restart using serve script

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel-website#31]
The `serve-docs` script does not enable fast iteration. I would expect to very easily be able to rebuild the docs. Pressing `r` does not work for me:

```
$ ./scripts/serve-docs.sh
..
Type q to quit, r to rebuild docs and restart jekyll
Rebuilding docs and restarting jekyll
The 'build' command is only supported from within a workspace.
```

**Comment by steren** [comment]
Did it work in the past @davidzchen ?

**Comment by davidzchen** [comment]
/cc @damienmg 

I haven't really tried using `r`, though, one issue I have run into is when the script attempts to lookup the pid and kill the Jekyll webserver it detaches, it is able to on macOS but fails to kill the process on Linux. Though, the `the 'build' command is only supported from within a workspace` is likely due to the [workaround](https://github.com/bazelbuild/bazel-website/blob/master/scripts/serve-docs.sh#L104) I added to work around jekyll/jekyll#6060 since the `pwd` when the script runs `build_and_serve` may not be in the workspace root anymore, which would be a bug.
